### ISSUE TITLE
Strategies.objects does not merge allOf with own schema

### ISSUE THREAD

**Issue by danielbradburn** [crunchr/openapi_conformance#1]
When you have the following schema:

```yaml
    Derived:
      allOf:
        - type: object
          properties:
            baseProperty:
              type: string
      properties:
        derivedProperty:
          type: string
```

``Strategies.objects`` will happily generated objects with ``baseProperty`` but properties from it's own schema (i.e. ``derivedProperty``) will not be generated. This is because it chooses either the allOf or it's own schema for generation (i.e. ``for schema in schema.all_of or [schema]``). This should be changed to include all_of and it's own schema.
